In [5]:
import json
import requests
import pandas as pd


In [7]:
import numpy as np
prices = np.array([10,20,30,40])
doubled = prices * 2
print(doubled) 

[20 40 60 80]


In [8]:
normalized = prices/100
print(normalized)

[0.1 0.2 0.3 0.4]


In [9]:
# element-wise operations
temperatures_c = (prices -32) *5/9
print (temperatures_c)

[-12.22222222  -6.66666667  -1.11111111   4.44444444]


In [ ]:

# Socrata API endpoint
url = "https://data.cityofnewyork.us/api/views/9btm-sxj3/rows.json?accessType=DOWNLOAD"

response = requests.get(url)
data = response.json()

# Extract the data rows
df = pd.DataFrame(data['data'], columns=[col['name'] for col in data['meta']['view']['columns']])
print(f"Dataset shape: {df.shape}")
print(df.head())